COLUMN_ALIASES = {
    "Are you self-employed?": "self_employed",
    "How many employees does your company or organization have?": "company_size",
    "Is your employer primarily a tech company/organization?": "tech_company",
    "Is your primary role within your company related to tech/IT?": "tech_role",
    "Does your employer provide mental health benefits as part of healthcare coverage?": "mh_benefits",
    "Do you know the options for mental health care available under your employer-provided coverage?": "know_options",
    "Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?": "employer_discussed_mh",
    "Does your employer offer resources to learn more about mental health concerns and options for seeking help?": "employer_resources",
    "Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?": "anonymity_protected",
    "If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:": "leave_difficulty",
    "Do you think that discussing a mental health disorder with your employer would have negative consequences?": "neg_consequences_employer",
    "Do you think that discussing a physical health issue with your employer would have negative consequences?": "neg_consequences_physical",
    "Would you feel comfortable discussing a mental health disorder with your coworkers?": "comfortable_coworkers",
    "Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?": "comfortable_supervisor",
    "Do you feel that your employer takes mental health as seriously as physical health?": "employer_takes_mh_serious",
    "Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?": "observed_neg_consequences",
    "Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?": "medical_coverage",
    "Do you know local or online resources to seek help for a mental health disorder?": "know_resources",
    "If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?": "reveal_clients",
    "If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?": "reveal_clients_impact",
    "If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?": "reveal_coworkers",
    "If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?": "reveal_coworkers_impact",
    "Do you believe your productivity is ever affected by a mental health issue?": "productivity_affected",
    "If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?": "pct_work_affected",
    "Do you have previous employers?": "has_previous_employers",
    "Have your previous employers provided mental health benefits?": "prev_mh_benefits",
    "Were you aware of the options for mental health care provided by your previous employers?": "prev_aware_options",
    "Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?": "prev_discussed_mh",
    "Did your previous employers provide resources to learn more about mental health issues and how to seek help?": "prev_resources",
    "Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?": "prev_anonymity",
    "Do you think that discussing a mental health disorder with previous employers would have negative consequences?": "prev_neg_consequences",
    "Do you think that discussing a physical health issue with previous employers would have negative consequences?": "prev_neg_physical",
    "Would you have been willing to discuss a mental health issue with your previous co-workers?": "prev_comfortable_coworkers",
    "Would you have been willing to discuss a mental health issue with your direct supervisor(s)?": "prev_comfortable_supervisor",
    "Did you feel that your previous employers took mental health as seriously as physical health?": "prev_mh_serious",
    "Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?": "prev_observed_neg",
    "Would you be willing to bring up a physical health issue with a potential employer in an interview?": "interview_physical",
    "Why or why not?": "interview_physical_why",
    "Would you bring up a mental health issue with a potential employer in an interview?": "interview_mental",
    "Do you feel that being identified as a person with a mental health issue would hurt your career?": "mh_hurts_career",
    "Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?": "coworkers_view_neg",
    "How willing would you be to share with friends and family that you have a mental illness?": "share_friends_family",
    "Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?": "observed_bad_response",
    "Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?": "observations_less_likely",
    "Do you have a family history of mental illness?": "family_history",
    "Have you had a mental health disorder in the past?": "past_disorder",
    "Do you currently have a mental health disorder?": "current_disorder",
    "If yes, what condition(s) have you been diagnosed with?": "diagnosed_conditions",
    "If maybe, what condition(s) do you believe you have?": "believed_conditions",
    "Have you been diagnosed with a mental health condition by a medical professional?": "professionally_diagnosed",
    "If so, what condition(s) were you diagnosed with?": "professional_diagnosis_detail",
    "Have you ever sought treatment for a mental health issue from a mental health professional?": "sought_treatment",
    "If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?": "interferes_treated",
    "If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?": "interferes_untreated",
    "What is your age?": "age",
    "What is your gender?": "gender",
    "What country do you live in?": "country_live",
    "What US state or territory do you live in?": "us_state_live",
    "What country do you work in?": "country_work",
    "What US state or territory do you work in?": "us_state_work",
    "Which of the following best describes your work position?": "work_position",
    "Do you work remotely?": "remote_work",
}